### ISSUE TITLE
Page fault error code I bit (bit 4) is never set on pre-NX processors

### ISSUE THREAD

**Issue by superfury** [blitz/baresifter#4]
When a page fault is thrown for the instruction fetching second page, the I-bit (bit 4 of the error code) is never set because it only happens on NX-enabled processors.
This breaks the analysis to incorrectly detect all instructions as 1-byte instructions.

**Comment by superfury** [comment]
I made a little support function for it:
```
static bool nx_supported()
{
return !(get_cpuid(0x80000000U).eax&0x80000000U)?0: /*Not possibly present*/
(
(get_cpuid(0x80000000U).eax<0x80000001U)?0: /*NX Leaf unsupported?*/
((get_cpuid(0x80000001U).edx>>20U)&1U) /*NX supported to bit 0!*/
);
}
```

And the replacement on main.c line 32/33:
```
bool has_nx = nx_supported(); /*NX supported? Also needs to be enabled.*/
bool incomplete_instruction_fetch = (ef.vector == 14 and
                                         (ef.error_code & (0b0101|(has_nx<<4U)) /* user space instruction fetch */) == (0b0100|(has_nx<<4U)) and
```

**Comment by superfury** [comment]
I can confirm the above patch properly compiling and running on my emulator (UniPCemu). If the documentation on CPUID is correct, it should be working on other emulators as well.

**Comment by superfury** [comment]
I've created a git diff of the added/changed working code:
[baresifter_nx_support.zip](https://github.com/blitz/baresifter/files/6758805/baresifter_nx_support.zip)

**Comment by superfury** [comment]
OK. The analysis/disasm/src/main.rs works, but line 12 ( https://github.com/blitz/baresifter/blob/master/analysis/disasm/src/main.rs#L12 ) needs to have 64 replaced by 32 for 32-bit processors (since x86_64 isn't downwards compatible with the x86 instruction set).

**Comment by blitz** [comment]
@superfury Thanks for the report! I'll look into this, but it will take a while.

**Comment by blitz** [comment]
@superfury Can you check whether master works for you and if not, re-open this issue?
